### ISSUE TITLE
App not working on Nexus 4

### ISSUE THREAD

**Issue by justinsalamon** [wifimapping/app#16]
Installed latest apk (from QR code) on Nexus 4 (LG) running Android 5.1.1. The app seems to have installed fine, but it never lists any wifi networks (I approved all permissions it requested upon installation). Just took it for a cycle, still didn't find anything.

**Comment by docmarionum1** [comment]
Do you have location services and wifi on?

**Comment by justinsalamon** [comment]
Yes, both are on

**Comment by docmarionum1** [comment]
Added logging.

Can you download the new version from: https://build.phonegap.com/apps/2025209/download/android/?qr_key=rLwXCvJfGdJSHdKanQyE

Then go to the menu on the left, open up "Log" and tell me what's in there?

**Comment by justinsalamon** [comment]
```
Starting Networks Controller
enableScanning=true
ionic ready
About to check Scanning Setting
handleScanningSetting
Enable Scanning
```

**Comment by justinsalamon** [comment]
@docmarionum1 also the log window is read/write right now (ie I can delete the log text or add text), you probably want to change that to read only

**Comment by docmarionum1** [comment]
I assumed you then moved around after  that showed up in the log and nothing else appeared?

**Comment by justinsalamon** [comment]
Correct
