### ISSUE TITLE
App not working on Galaxy Nexus SCH-i515

### ISSUE THREAD

**Issue by cmydlarz** [wifimapping/app#19]
WiFi results page is never populated after a walk to and from work. Device is old, running Android 4.2.2. All permissions were granted on install and I have made sure that locations services and wifi are both on.

Device has no SIM card installed.

**Comment by docmarionum1** [comment]
Added logging.

Can you download the new version from: https://build.phonegap.com/apps/2025209/download/android/?qr_key=rLwXCvJfGdJSHdKanQyE

Then go to the menu on the left, open up "Log" and tell me what's in there?
