### ISSUE TITLE
Figure out Requirements for IRB Process

### ISSUE THREAD

**Issue by docmarionum1** [wifimapping/app#26]
https://www.nyu.edu/research/resources-and-support-offices/getting-started-withyourresearch/human-subjects-research.html

**Comment by yunongcao** [comment]
After reading a couple of material on NYU's site, I found our project might not belong to human subject research (HSR) according to the [IRB Decision Tree](https://www.nyu.edu/content/dam/nyu/research/documents/IRB/IRBDecisionTree.pdf).  
A more formal checklist is [Checklist for Determining Whether a Project Involves Human Subjects](https://www.nyu.edu/content/dam/nyu/research/documents/IRB/NotHSResearch.doc). I don't know whether we had already go over this. If we meet all criteria on the list, then we don't even need to fill out the IRB Petition.  

---

However, if we have already determined our research to be an HSR case, we need to the following stuff:
- Finish CITI course which consists of 16 learning modules (at least 15 minutes per module recommended). All NYU Investigators are required to take the Collaborative Institutional Training Initiative (CITI) course for Social and Behavioral Research Scientists. 
- Register for [Cayuse Research Suite](https://nyu.cayuse424.com/): this takes at least 2 business days for activation. (I have already sent my application, but so far my account has not been activated yet.)
- Create a New Protocol in Cayuse IRB: Follow the guide on https://www.nyu.edu/content/dam/nyu/research/documents/IRB/welcometocayuseirb.pdf
- Check the Status of an Existing Protocol: Follow the guide above 
- Edit the protocol if needed

If anyone has his account activated on  [Cayuse Research Suite](https://nyu.cayuse424.com/), a protocol can be created and submitted now.

**Comment by justinsalamon** [comment]
@yunongcao see my comments on slack
