### ISSUE TITLE
Enable scanning toggles off when app moves to background

### ISSUE THREAD

**Issue by cmydlarz** [wifimapping/app#55]
On the Samsung device running Android 4.2.2 the "Enable scanning" switch toggles off when the app is put to the background (app version 0.3.1)

**Comment by docmarionum1** [comment]
What do you mean by put to the background?  Just going to the home screen?  Does the notification about scanning go away?  Is it possible to get the logs?

**Comment by cmydlarz** [comment]
Ill do my best to get him to send me the log info. Yea, the toggle switches when the phone goes to the home screen then the app is brought back to the foreground. We currently have him open the app, then press the lock button which seems to work as the scanning toggle is ON when you unlock the phone and see the app

**Comment by docmarionum1** [comment]
Closing as it seems to only happen on a version of android we've decided not to support.
