### ISSUE TITLE
Start on boot not functioning

### ISSUE THREAD

**Issue by cmydlarz** [wifimapping/app#56]
Samsung device running Android 4.2.2 does not start app on boot (app version 0.3.1). Start on boot switched on in app settings

**Comment by docmarionum1** [comment]
Notice any error in the logs when toggling start on boot?

**Comment by cmydlarz** [comment]
This was spotted late last night after Id handed the phone over to the driver. Ill get in touch with him and see if he can let me know. We currently have him checking it at the start of his shift to make sure its running and scanning is enabled

**Comment by docmarionum1** [comment]
Closing as it seems to only happen on a version of android we've decided not to support.
